---
title: Meyer Truck And Alignment Website
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  content-different:
    title: content-different
    output: true
  services:
    title: services
    output: true
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
